module Currency
  JPY = "JPY"
  BTC = "BTC"
  ETH = "ETH"
  ETC = "ETC"
  DAO = "DAO"
  LSK = "LSK"
  FCT = "FCT"
  XMR = "XMR"
  REP = "REP"
  XRP = "XRP"
  ZEC = "ZEC"

  module Pair
    BTC_JPY = "btc_jpy"
    ETH_JPY = "eth_jpy"
    ETC_JPY = "etc_jpy"
    DAO_JPY = "dao_jpy"
    LSK_JPY = "lsk_jpy"
    FCT_JPY = "fct_jpy"
    XMR_JPY = "xmr_jpy"
    REP_JPY = "rep_jpy"
    XRP_JPY = "xrp_jpy"
    ZEC_JPY = "zec_jpy"
    ETH_BTC = "eth_btc"
    ETC_BTC = "etc_btc"
    LSK_BTC = "lsk_btc"
    FCT_BTC = "fct_btc"
    XMR_BTC = "xmr_btc"
    REP_BTC = "rep_btc"
    XRP_BTC = "xrp_btc"
    ZEC_BTC = "zec_btc"
  end
end