module Currency
  JPY = "JPY"
  BTC = "BTC"
  ETH = "ETH"
  ETC = "ETC"
  LSK = "LSK"
  XRP = "XRP"
  XEM = "XEM"
  LTC = "LTC"
  BCH = "BCH"
  MONA = "MONA"
  XLM = "XLM"
  QTUM = "QTUM"
  BAT = "BAT"
  IOST = "IOST"
  ENJ = "ENJ"
  OMG = "OMG"
  XYM = "XYM"

  module Pair
    # base_jpy
    BTC_JPY = "btc_jpy"
    ETH_JPY = "eth_jpy"
    ETC_JPY = "etc_jpy"
    LSK_JPY = "lsk_jpy"
    XRP_JPY = "xrp_jpy"
    XEM_JPY = "xem_jpy"
    LTC_JPY = "ltc_jpy"
    BCH_JPY = "bch_jpy"
    MONA_JPY = "mona_jpy"
    XLM_JPY = "xlm_jpy"
    QTUM_JPY = "qtum_jpy"
    BAT_JPY = "bat_jpy"
    IOST_JPY = "iost_jpy"
    ENJ_JPY = "enj_jpy"
    OMG_JPY = "omg_jpy"
    XYM_JPY = "xym_jpy"
    # base_btc
    ETH_BTC = "eth_btc"
    ETC_BTC = "etc_btc"
    LSK_BTC = "lsk_btc"
    XRP_BTC = "xrp_btc"
    XEM_BTC = "xem_btc"
    LTC_BTC = "ltc_btc"
    BCH_BTC = "bch_btc"
    MONA_BTC = "mona_btc"
    XLM_BTC = "xlm_btc"
    QTUM_BTC = "qtum_btc"
    BAT_BTC = "bat_btc"
    IOST_BTC = "iost_btc"
    ENJ_BTC = "enj_btc"
    OMG_BTC = "omg_btc"
    XYM_BTC = "xym_btc"
  end
end
