module Currency
  JPY = "JPY"
  BTC = "BTC"
  ETH = "ETH"
  ETC = "ETC"
  DAO = "DAO"
  LSK = "LSK"
  FCT = "FCT"
  XMR = "XMR"
  REP = "REP"
  XRP = "XRP"
  ZEC = "ZEC"
  XEM = "XEM"
  LTC = "LTC"
  DASH = "DASH"
  BCH = "BCH"
  MONA = "MONA"

  module Pair
    BTC_JPY = "btc_jpy"
    ETH_JPY = "eth_jpy"
    ETC_JPY = "etc_jpy"
    DAO_JPY = "dao_jpy"
    LSK_JPY = "lsk_jpy"
    FCT_JPY = "fct_jpy"
    XMR_JPY = "xmr_jpy"
    REP_JPY = "rep_jpy"
    XRP_JPY = "xrp_jpy"
    ZEC_JPY = "zec_jpy"
    XEM_JPY = "xem_jpy"
    LTC_JPY = "ltc_jpy"
    DASH_JPY = "dash_jpy"
    BCH_JPY = "bch_jpy"
    MONA_JPY = "mona_jpy"
    ETH_BTC = "eth_btc"
    ETC_BTC = "etc_btc"
    LSK_BTC = "lsk_btc"
    FCT_BTC = "fct_btc"
    XMR_BTC = "xmr_btc"
    REP_BTC = "rep_btc"
    XRP_BTC = "xrp_btc"
    ZEC_BTC = "zec_btc"
    XEM_BTC = "xem_btc"
    LTC_BTC = "ltc_btc"
    DASH_BTC = "dash_btc"
    BCH_BTC = "bch_btc"
    MONA_BTC = "mona_btc"
  end
end